name: Test

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install application dependencies
      run: poetry install
    - name: Run flake8
      run: poetry run flake8 mbdata_graphql
    - name: Run mypy
      run: poetry run mypy mbdata_graphql
    - name: Run pytest
      run: poetry run pytest
